version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version 
      - docker login -u AWS -p $(aws ecr get-login-password --region eu-west-1) $REGISTRY
      - REPOSITORY_URI=$REGISTRY
      - echo $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:stg-latest .
      - docker tag $REPOSITORY_URI:stg-latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:stg-latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - curl -X POST https://portainer.spaceriders.io/api/webhooks/7709b025-fd72-41c2-8288-e366f6c241b5
      - curl -X POST https://portainer.spaceriders.io/api/webhooks/1be32d25-470f-40a4-a78b-b5fdbe119a88
      - curl -X POST https://portainer.spaceriders.io/api/webhooks/be4aedc9-44fc-445a-a82f-ca4da8142340
