version: '3.7'

services:    
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      DB_URL: mongodb://root:example@db:27017/

  cronjob:
    build: .
    environment:
      - DB_URL=mongodb://root:example@db:27017/
      - PYTHONUNBUFFERED=0

    working_dir: "/app/src"
    entrypoint: ["python", "-m", "apps.cronjobs.__init__"]
    volumes:
      - ".:/app"

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  cache:
    image: bitnami/memcached:latest
    restart: always
    ports:
      - 11211:11211
    environment:
      MEMCACHED_MAX_CONNECTIONS: 5000




